"""
Reflective ICP Engine for the Cognition Engine.

This module provides reflection capabilities to enhance analysis
through self-criticism and improvement.
"""

import logging
import time
from typing import Dict, List, Optional, Any, Union
import openai
import json
from openai import OpenAI

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ReflectionAgent:
    """
    Agent that provides self-critique and improvement capabilities
    for other parts of the system.
    """
    
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize a new reflection agent.
        
        Args:
            api_key: Optional API key for OpenAI services
        """
        self.api_key = api_key
        # Try to get API key from environment if not provided
        if not self.api_key:
            try:
                import os
                self.api_key = os.environ.get("OPENAI_API_KEY")
            except:
                pass
    
    def reflect_on_output(self, original_output: str, iteration: int = 1) -> str:
        """
        Reflect on and improve the given output.
        
        Args:
            original_output: The output to reflect on and improve
            iteration: The current reflection iteration (higher means more depth)
            
        Returns:
            Improved output after reflection
        """
        logger.info(f"Running reflection iteration {iteration} on output of length {len(original_output)}")
        
        # In a real implementation, this would call the OpenAI API
        # For now, we'll simulate reflection by adding a note and slight modifications
        
        # Simulate reflection processing time
        time.sleep(0.5)  # Half second delay to simulate reflection
        
        # For demo purposes, we'll just add some "improvements"
        reflection = f"""
Reflection #{iteration}:
- The original output could be more specific
- It lacks quantitative evidence in some areas
- The structure could be improved for clarity
- Some insights could be more actionable
        """.strip()
        
        # Simulate improved output (in reality, this would be generated by an LLM)
        improved_output = original_output
        
        # Make some token improvements based on iteration
        if "actionable" not in improved_output:
            improved_output += "\n\nAdditional actionable recommendation: "
            improved_output += "Consider segmenting customers by industry vertical for more targeted outreach."
            
        if iteration > 1 and "quantitative" not in improved_output:
            improved_output += "\n\nQuantitative insight: "
            improved_output += "Companies with 200+ employees show 35% higher conversion rates than smaller businesses."
            
        if iteration > 2:
            improved_output += "\n\nStrategic consideration: "
            improved_output += "Market timing affects deal closure rates significantly, with Q4 showing 28% better performance than Q2."
        
        logger.info(f"Completed reflection iteration {iteration}")
        return improved_output

class ReflectiveICPEngine:
    """
    Engine that enhances ICP analysis through reflective capabilities.
    """
    
    def __init__(self, reflection_agent: Optional[ReflectionAgent] = None):
        """
        Initialize a new reflective ICP engine.
        
        Args:
            reflection_agent: Optional reflection agent to use
        """
        self.reflection_agent = reflection_agent or ReflectionAgent()
    
    def enhance_output(self, original_output: str, steps: int = 1) -> str:
        """
        Enhance output through multiple steps of reflection.
        
        Args:
            original_output: The original output to enhance
            steps: Number of reflection steps to perform
            
        Returns:
            Enhanced output after reflection
        """
        if steps <= 0:
            return original_output
        
        logger.info(f"Starting output enhancement with {steps} reflection steps")
        current_output = original_output
        
        for i in range(1, steps + 1):
            current_output = self.reflection_agent.reflect_on_output(
                current_output, 
                iteration=i
            )
        
        logger.info(f"Completed output enhancement with {steps} reflection steps")
        return current_output
    
    def analyze(self, data: Dict[str, Any], question: str, categories: List[str] = None, reflection_steps: int = 1) -> Dict[str, Any]:
        """
        Analyze data to generate insights based on a specific question and categories.
        
        Args:
            data: Dictionary containing the data to analyze
            question: The question to answer with the analysis
            categories: List of categories to guide the analysis approach
            reflection_steps: Number of reflection steps to apply
            
        Returns:
            Dictionary containing generated insights
        """
        logger.info(f"Starting analysis for question: {question}")
        categories = categories or ["general_analysis"]
        
        # Generate insights using LLM-based dynamic generation
        insights = self._generate_insights_with_llm(question, data)

        # Apply reflection to enhance the insights if requested
        if reflection_steps > 0:
            # Convert insights to string format for reflection
            insights_text = json.dumps(insights, indent=2)
            
            # Apply reflection
            enhanced_insights_text = self.enhance_output(insights_text, steps=reflection_steps)
            
            # In a real implementation, parse enhanced text back to dict with improvements
            # For this demo, we'll just annotate it and add a simulated improvement
            insights["reflection_applied"] = True
            insights["reflection_steps"] = reflection_steps
            
            # Simulate improvement by adding additional insights
            if "recommendations" in insights and len(insights["recommendations"]) > 0:
                insights["recommendations"].append(
                    "Consider conducting customer interviews in your top-performing segments to better understand their specific value drivers and decision criteria."
                )
                
            if "supporting_points" in insights and len(insights["supporting_points"]) > 0:
                insights["supporting_points"].append(
                    "Multivariate analysis suggests that the combination of industry, size, and geography factors creates compound effects on performance metrics."
                )
                
            logger.info(f"Applied {reflection_steps} reflection steps to enhance analysis insights")
        
        return insights

    def _generate_insights_with_llm(self, question: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Use OpenAI's GPT model to dynamically generate insights.
        """
        client = OpenAI()

        prompt = f"""
You are a CRM data analyst. Analyze the following ICP triangulation data and answer the user's question with insights, trends, and strategic recommendations.

Question: {question}

Data:
{json.dumps(data, indent=2)}

Respond in JSON format with fields:
- main_insight: str
- supporting_points: list of strings
- recommendations: list of strings
- trends: list of strings
        """

        response = client.responses.create(
            model="gpt-4",
            input=[
                {"role": "system", "content": "You are a helpful CRM data analyst."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )
        print(f"The response is \n {response}")
        text_response = response.output_text
        try:
            return json.loads(text_response)
        except json.JSONDecodeError:
            return {
                "main_insight": text_response,
                "supporting_points": [],
                "recommendations": [],
                "trends": [],
                "error": "Could not parse response as JSON."
            }
    
    def generate_icp_definition(self, data: Dict[str, Any], reflection_steps: int = 1) -> Dict[str, Any]:
        """
        Generate an ICP definition using reflection for improvement.
        
        Args:
            data: Input data for ICP generation
            reflection_steps: Number of reflection steps to perform
            
        Returns:
            Enhanced ICP definition
        """
        # Start with a basic ICP definition
        icp_definition = {
            "name": "Initial ICP Definition",
            "description": "Basic definition of ideal customer profile",
            "criteria": [
                {
                    "field": "industry",
                    "values": ["Technology", "Healthcare"],
                    "weight": 0.3,
                    "description": "Primary industries showing best results"
                },
                {
                    "field": "company_size",
                    "values": ["Mid-market"],
                    "weight": 0.2,
                    "description": "Company size by employee count or revenue"
                }
            ]
        }
        
        # Convert to string representation for reflection
        import json
        icp_as_text = json.dumps(icp_definition, indent=2)
        
        # Enhance through reflection
        if reflection_steps > 0:
            enhanced_text = self.enhance_output(icp_as_text, steps=reflection_steps)
            
            # In a real implementation, this would parse the enhanced text back to a dict
            # For now, we'll just annotate that reflection was done
            icp_definition["reflection_applied"] = True
            icp_definition["reflection_steps"] = reflection_steps
            icp_definition["name"] = f"Enhanced ICP Definition (with {reflection_steps} reflection steps)"
        
        return icp_definition 