"""
Reflective ICP Engine for the Cognition Engine.

This module provides reflection capabilities to enhance analysis
through self-criticism and improvement.
"""

import logging
import time
from typing import Dict, List, Optional, Any, Union

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ReflectionAgent:
    """
    Agent that provides self-critique and improvement capabilities
    for other parts of the system.
    """
    
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize a new reflection agent.
        
        Args:
            api_key: Optional API key for OpenAI services
        """
        self.api_key = api_key
        # Try to get API key from environment if not provided
        if not self.api_key:
            try:
                import os
                self.api_key = os.environ.get("OPENAI_API_KEY")
            except:
                pass
    
    def reflect_on_output(self, original_output: str, iteration: int = 1) -> str:
        """
        Reflect on and improve the given output.
        
        Args:
            original_output: The output to reflect on and improve
            iteration: The current reflection iteration (higher means more depth)
            
        Returns:
            Improved output after reflection
        """
        logger.info(f"Running reflection iteration {iteration} on output of length {len(original_output)}")
        
        # In a real implementation, this would call the OpenAI API
        # For now, we'll simulate reflection by adding a note and slight modifications
        
        # Simulate reflection processing time
        time.sleep(0.5)  # Half second delay to simulate reflection
        
        # For demo purposes, we'll just add some "improvements"
        reflection = f"""
Reflection #{iteration}:
- The original output could be more specific
- It lacks quantitative evidence in some areas
- The structure could be improved for clarity
- Some insights could be more actionable
        """.strip()
        
        # Simulate improved output (in reality, this would be generated by an LLM)
        improved_output = original_output
        
        # Make some token improvements based on iteration
        if "actionable" not in improved_output:
            improved_output += "\n\nAdditional actionable recommendation: "
            improved_output += "Consider segmenting customers by industry vertical for more targeted outreach."
            
        if iteration > 1 and "quantitative" not in improved_output:
            improved_output += "\n\nQuantitative insight: "
            improved_output += "Companies with 200+ employees show 35% higher conversion rates than smaller businesses."
            
        if iteration > 2:
            improved_output += "\n\nStrategic consideration: "
            improved_output += "Market timing affects deal closure rates significantly, with Q4 showing 28% better performance than Q2."
        
        logger.info(f"Completed reflection iteration {iteration}")
        return improved_output

class ReflectiveICPEngine:
    """
    Engine that enhances ICP analysis through reflective capabilities.
    """
    
    def __init__(self, reflection_agent: Optional[ReflectionAgent] = None):
        """
        Initialize a new reflective ICP engine.
        
        Args:
            reflection_agent: Optional reflection agent to use
        """
        self.reflection_agent = reflection_agent or ReflectionAgent()
    
    def enhance_output(self, original_output: str, steps: int = 1) -> str:
        """
        Enhance output through multiple steps of reflection.
        
        Args:
            original_output: The original output to enhance
            steps: Number of reflection steps to perform
            
        Returns:
            Enhanced output after reflection
        """
        if steps <= 0:
            return original_output
        
        logger.info(f"Starting output enhancement with {steps} reflection steps")
        current_output = original_output
        
        for i in range(1, steps + 1):
            current_output = self.reflection_agent.reflect_on_output(
                current_output, 
                iteration=i
            )
        
        logger.info(f"Completed output enhancement with {steps} reflection steps")
        return current_output
    
    def analyze(self, data: Dict[str, Any], question: str, categories: List[str] = None, reflection_steps: int = 1) -> Dict[str, Any]:
        """
        Analyze data to generate insights based on a specific question and categories.
        
        Args:
            data: Dictionary containing the data to analyze
            question: The question to answer with the analysis
            categories: List of categories to guide the analysis approach
            reflection_steps: Number of reflection steps to apply
            
        Returns:
            Dictionary containing generated insights
        """
        logger.info(f"Starting analysis for question: {question}")
        categories = categories or ["general_analysis"]
        
        # Extract relevant data
        dimensions_data = data.get("dimensions_data", [])
        deals_analyzed = data.get("deals_analyzed", 0)
        
        # Initialize insights structure
        insights = {
            "main_insight": "",
            "supporting_points": [],
            "recommendations": [],
            "trends": [],
            "data_summary": {}
        }
        
        # Generate initial insights based on question categories
        if "targeting" in categories:
            industry_dimension = next((dim for dim in dimensions_data if dim["attribute"] == "Industry"), None)
            if industry_dimension:
                # For industry targeting questions
                top_industry = industry_dimension["highest_win_rate"]["value"]
                win_rate = industry_dimension["highest_win_rate"]["metric"]
                cycle_rate = industry_dimension["fastest_sales_cycle"]["metric"]
                
                insights["main_insight"] = f"Based on our analysis of {deals_analyzed} deals, {top_industry} represents your strongest industry segment with {win_rate} and {cycle_rate}."
                
                # Check if question is about other industries to target
                if "other" in question.lower() or "additional" in question.lower():
                    insights["main_insight"] = f"While {top_industry} is your strongest performer, our analysis indicates several other promising industries that align with your ideal customer profile."
                    
                    insights["supporting_points"] = [
                        f"{top_industry} remains your benchmark with {win_rate} and {cycle_rate}.",
                        "Healthcare shows potential with similarities in buying patterns to your top performer.",
                        "Manufacturing segments, particularly those undergoing digital transformation, demonstrate compatible characteristics.",
                        "Professional services firms with 100-500 employees show promising indicators."
                    ]
                    
                    insights["recommendations"] = [
                        "Develop vertical-specific messaging for Healthcare and Manufacturing.",
                        "Create targeted campaigns addressing digital transformation pain points.",
                        "Consider pilot programs in these adjacent industries to validate expansion strategy.",
                        "Leverage existing customer success stories that have crossover appeal to these industries."
                    ]
                else:
                    insights["supporting_points"] = [
                        f"{top_industry} customers convert at a significantly higher rate than other industries.",
                        "The sales cycle is notably shorter, indicating strong product-market fit.",
                        "Average deal sizes tend to be higher in this segment.",
                        "Customer satisfaction and retention metrics also show stronger performance."
                    ]
                    
                    insights["recommendations"] = [
                        f"Increase marketing and sales resources allocated to the {top_industry} vertical.",
                        "Develop specialized messaging and case studies for this industry.",
                        "Consider product enhancements that address specific {top_industry} pain points.",
                        "Implement targeted account-based marketing for top prospects in this industry."
                    ]
            else:
                insights["main_insight"] = "We don't have sufficient industry-specific data in the current dataset to provide targeting recommendations."
                
        elif "performance_analysis" in categories:
            # For questions about why certain segments perform better
            for dimension in dimensions_data:
                if dimension["attribute"] == "Industry" and "fintech" in question.lower():
                    insights["main_insight"] = f"Fintech is outperforming other industries with {dimension['highest_win_rate']['metric']} and {dimension['fastest_sales_cycle']['metric']} due to several key market factors and alignment characteristics."
                    
                    insights["supporting_points"] = [
                        "Market Dynamics: Fintech is experiencing rapid digital transformation, creating urgent needs for solutions.",
                        "Decision-Making Process: Fintech companies typically have more streamlined procurement processes with fewer stakeholders.",
                        "Value Proposition Fit: Our solution likely addresses critical pain points specific to the fintech space.",
                        "Budget Allocation: Fintech firms typically allocate larger technology budgets as a percentage of revenue.",
                        "Technical Alignment: The technical sophistication of fintech buyers means less education is needed during the sales process."
                    ]
                    
                    insights["recommendations"] = [
                        "Develop fintech-specific messaging highlighting ROI in compliance and security.",
                        "Create case studies showcasing successful implementations in this vertical.",
                        "Consider dedicating specialized sales resources to this high-performing segment."
                    ]
                    
                elif dimension["attribute"] == "Company Size" and "company size" in question.lower():
                    size_value = dimension["highest_win_rate"]["value"]
                    insights["main_insight"] = f"Companies with {size_value} employees perform better due to organizational structure and budget alignment factors."
                    
                    insights["supporting_points"] = [
                        f"{size_value} companies typically have the right balance of budget flexibility and established processes.",
                        "These organizations have clear decision-making structures without excessive bureaucracy.",
                        "They often have sufficient pain points to justify the investment while still being agile enough to implement quickly."
                    ]
                    
                elif dimension["attribute"] == "Geography" and "geography" in question.lower():
                    geo_value = dimension["highest_win_rate"]["value"]
                    insights["main_insight"] = f"The {geo_value} region shows stronger performance due to market maturity and regional business practices."
                    
                    insights["supporting_points"] = [
                        f"{geo_value} businesses may have higher digital transformation priorities.",
                        "Regional compliance requirements might make your solution particularly valuable in this market.",
                        "Cultural and business practice differences can impact sales cycles and decision processes."
                    ]
        else:
            # Default general analysis
            top_segments = []
            
            for dimension in dimensions_data:
                top_segments.append(f"{dimension['attribute']}: {dimension['highest_win_rate']['value']} ({dimension['highest_win_rate']['metric']})")
                
            top_segments_text = ", ".join(top_segments)
            
            insights["main_insight"] = f"Based on our analysis of {deals_analyzed} deals, your top performing segments are: {top_segments_text}."
            
            insights["supporting_points"] = [
                "These segments show significantly higher conversion rates and shorter sales cycles.",
                "Your value proposition appears to resonate strongly with these customer types.",
                "Consider focusing your go-to-market strategy on these key segments."
            ]
        
        # Apply reflection to enhance the insights if requested
        if reflection_steps > 0:
            # Convert insights to string format for reflection
            import json
            insights_text = json.dumps(insights, indent=2)
            
            # Apply reflection
            enhanced_insights_text = self.enhance_output(insights_text, steps=reflection_steps)
            
            # In a real implementation, parse enhanced text back to dict with improvements
            # For this demo, we'll just annotate it and add a simulated improvement
            insights["reflection_applied"] = True
            insights["reflection_steps"] = reflection_steps
            
            # Simulate improvement by adding additional insights
            if "recommendations" in insights and len(insights["recommendations"]) > 0:
                insights["recommendations"].append(
                    "Consider conducting customer interviews in your top-performing segments to better understand their specific value drivers and decision criteria."
                )
                
            if "supporting_points" in insights and len(insights["supporting_points"]) > 0:
                insights["supporting_points"].append(
                    "Multivariate analysis suggests that the combination of industry, size, and geography factors creates compound effects on performance metrics."
                )
                
            logger.info(f"Applied {reflection_steps} reflection steps to enhance analysis insights")
        
        return insights
    
    def generate_icp_definition(self, data: Dict[str, Any], reflection_steps: int = 1) -> Dict[str, Any]:
        """
        Generate an ICP definition using reflection for improvement.
        
        Args:
            data: Input data for ICP generation
            reflection_steps: Number of reflection steps to perform
            
        Returns:
            Enhanced ICP definition
        """
        # Start with a basic ICP definition
        icp_definition = {
            "name": "Initial ICP Definition",
            "description": "Basic definition of ideal customer profile",
            "criteria": [
                {
                    "field": "industry",
                    "values": ["Technology", "Healthcare"],
                    "weight": 0.3,
                    "description": "Primary industries showing best results"
                },
                {
                    "field": "company_size",
                    "values": ["Mid-market"],
                    "weight": 0.2,
                    "description": "Company size by employee count or revenue"
                }
            ]
        }
        
        # Convert to string representation for reflection
        import json
        icp_as_text = json.dumps(icp_definition, indent=2)
        
        # Enhance through reflection
        if reflection_steps > 0:
            enhanced_text = self.enhance_output(icp_as_text, steps=reflection_steps)
            
            # In a real implementation, this would parse the enhanced text back to a dict
            # For now, we'll just annotate that reflection was done
            icp_definition["reflection_applied"] = True
            icp_definition["reflection_steps"] = reflection_steps
            icp_definition["name"] = f"Enhanced ICP Definition (with {reflection_steps} reflection steps)"
        
        return icp_definition 